# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lawrence's Personal Blog Site
email: lawrencedai528@gamil.com
description: > # this means to ignore newlines until "baseurl:"
  A seasoned software engineer who live up to the high standard.
  Starts with scalable, performant architectures, continue to continuous delivery pipeline, 
  down to day to day Test Driven Development expressive, high quality code.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ldai-www.noip.us" # the base hostname & protocol for your site
twitter_username: ldai528
github_username:  ldai

# Build settings
markdown: kramdown
